'''This code has been written after watching this: https://www.youtube.com/watch?v=bEyTZ5ZZxZs&t=292s 
Briefly it draws consecutive foreward and backward slashes depending on a probability factor.
Probability is generated by checking a random number between 0 and 1  with 0.5 and if it's greater than 0.5,
we draw a slash(or backslash) else we draw the other one.
 By changing the probability factor we cn generate more patterns.
 For more information: https://10print.org/ '''

### Sahil Islam ###
### 04/06/2020 ###

import pygame
import random

pygame.init()

display_width = 900
display_height = 650

black = [0, 0, 0]
white = [255, 255, 255]
green = [0, 255, 0]
red = [255, 0, 0]

screen = pygame.display.set_mode((display_width, display_height))
clock = pygame.time.Clock()
pygame.display.set_caption("10 Print")


def slash(x, y, h):
    pygame.draw.line(screen, white, [x + h, y], [x, y + h])


def backslash(x, y, h):
    pygame.draw.line(screen, white, [x, y], [x + h, y + h])


def squre(x, y, h, color):
    pygame.draw.rect(screen, color, [x, y, x + h, y + h])


def circle(x, y, h, color):
    pygame.draw.circle(screen, color, [int(x), int(y)], h)


x = 0
y = 0
h = 20
screen.fill(black)
game_exit = False
while not game_exit:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            quit()

    if random.random() < 0.5:
        slash(x, y, h)
        #squre(x, y, h, white)
        # circle(x, y, h, white)
    else:
        backslash(x, y, h)
        #squre(x, y, h, black)
        # circle(x, y, h, black)
    x += h
    if x > display_width or x + h > display_width:
        x = 0
        y += h
    if x > display_width and y > display_height:
        x = 0
        y = 0

    pygame.display.update()
    clock.tick(50)
